<a href="https://colab.research.google.com/github/yseoyoung/python/blob/main/%ED%86%B5%EA%B3%84%EB%B6%84%EC%84%9D%EC%8B%9C%EA%B0%81%ED%99%94_Numpy_%EC%86%8C%EA%B0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 소개

In [ ]:
import numpy as np

numpy는 선형 시퀀스를 배열 개체로 취급

In [ ]:
ls = [1,2,3]
arr = np.array(ls)
print(arr)

[1 2 3]


In [ ]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
print("구조",arr.shape)
print("차원:",arr.ndim) #ndim : 차원

구조 (3,)
차원: 1


다차원 배열

In [ ]:
ls = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
arr = np.array(ls)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print("구조",arr.shape)
print("차원:",arr.ndim) # ndim : 차원

구조 (4, 3)
차원: 2


# 다양한 방법의 생성

In [ ]:
z_arr = np.zeros(10) # 주어진 shape나 type에 맞춰 zero들로 가득한 array를 반환하는 함수
print(z_arr)
print("구조:",z_arr.shape)
print("차원:",z_arr.ndim)
print("원소 형식:",z_arr.dtype) #default는 float(실수)- 0은 정수일 수도 있고 실수일 수도 있다는 점, optional하기에 굳이 선택하지 않아도 됨

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
구조: (10,)
차원: 1
원소 형식: float64


In [ ]:
z_arr = np.zeros((2,3))
print(z_arr)
print("구조:",z_arr.shape)
print("차원:",z_arr.ndim)
print("원소 형식:",z_arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
구조: (2, 3)
차원: 2
원소 형식: float64


In [ ]:
def view_arr_info(arr):
  print(arr)
  print("구조:",arr.shape)
  print("차원:",arr.ndim)
  print("원소 형식:",arr.dtype)

In [ ]:
z_arr = np.zeros((3,2,4),dtype=int)
view_arr_info(z_arr)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
구조: (3, 2, 4)
차원: 3
원소 형식: int64


In [ ]:
o_arr = np.ones(10)
view_arr_info(o_arr)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
구조: (10,)
차원: 1
원소 형식: float64


In [ ]:
s_arr = np.arange(100)
view_arr_info(s_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
구조: (100,)
차원: 1
원소 형식: int64


In [ ]:
s_arr = np.arange(50,100)
view_arr_info(s_arr)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
구조: (50,)
차원: 1
원소 형식: int64


In [ ]:
r_arr = np.random.randint(0,100,size=10,dtype=int)
view_arr_info(r_arr)

[80 85 62 39 64 70 53  2 22 48]
구조: (10,)
차원: 1
원소 형식: int64


#기본적인 사용

In [ ]:
a1 = np.arange(1,100)
view_arr_info(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
구조: (99,)
차원: 1
원소 형식: int64


In [ ]:
print(a1[4]) #인덱스를 통해 원소에 접근
a1[4]=9
print(a1[4])

5
9


In [ ]:
print(a1[2:8]) #슬라이스를 통해 부분 원소를 선택
print(a1[:8])
print(a1[8:])

[3 4 9 6 7 8]
[1 2 3 4 9 6 7 8]
[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80
 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [ ]:
a1 = np.arange(0,100)
view_arr_info(a1)
a2 = a1.reshape(5,20)
view_arr_info(a2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
구조: (100,)
차원: 1
원소 형식: int64
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
구조: (5, 20)
차원: 2
원소 형식: int64


In [ ]:
print(a2[0]) #인덱스 0인 원소: 리스트[0,1,2,....,19]
print(a2[0][2]) #인덱스 0인 원소: 리스트[0,1,2,....,19]의 인덱스 2인 원소

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
2


In [ ]:
#음의 정수로 인덱스를 표현하면 뒤에서부터 접근(-1부터 시작)
print(a2[0][-1]) #인덱스 0인 원소: 리스트[0,1,2,....,19]의 인덱스 -1인 원소

19


#구조 변경

In [ ]:
a1 = np.arange(100)
view_arr_info(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
구조: (100,)
차원: 1
원소 형식: int64


In [ ]:
a2 = a1.reshape((10,-1)) #-1로 하면 알아서 10행에 맞게 열이 자동으로 생성됨
view_arr_info(a2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
구조: (10, 10)
차원: 2
원소 형식: int64


In [ ]:
a1 = np.arange(784)
view_arr_info(a1)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [ ]:
a2 = a1.reshape(28,-1) #열의 크기를 모를 때 자동으로 생성됨
view_arr_info(a2)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27]
 [ 28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
   46  47  48  49  50  51  52  53  54  55]
 [ 56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
   74  75  76  77  78  79  80  81  82  83]
 [ 84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
  102 103 104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
  130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159 160 161 162 163 164 165 166 167]
 [168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185
  186 187 188 189 190 191 192 193 194 195]
 [196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213
  214 215 216 217 218 219 220 221 222 223]
 [224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 23

#쉬어가는 코너

In [ ]:
from tensorflow import keras

In [ ]:
data = keras.datasets.mnist.load_data() #손글씨 데이터를 다운로드

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
train_data, test_data = data #학습용 데이터, 평가용 데이터로 분리
image_train, label_train = train_data #이미지 ,실제값

In [ ]:
print(image_train.shape)
print(label_train.shape)

(60000, 28, 28)
(60000,)


In [ ]:
for r in range(28):
  for c in range(28):
    if(image_train[0][r][c] == 0 ):
      print("  ", end='')
    else:
      print("■", end='')
  print()
print(label_train[0])

                                                        
                                                        
                                                        
                                                        
                              ■■■■■                
                            ■■■■■■                
                          ■■■■■■■■■            
                      ■■■■■■■■■■■            
                      ■■■■■■■■■■■            
                    ■■■■■■■■■■■■            
                  ■■■■■■■■■    ■■■          
                ■■■■■■            ■■■          
              ■■■■■■■            ■■■          
              ■■■■                  ■■■          
              ■■■                    ■■■          
            ■■■■                    ■■■          
            ■■■■                ■■■■■          
            ■■■                ■■■■■            
            ■■■              ■■■■                
            ■■■            ■■■■               