<a href="https://colab.research.google.com/github/yseoyoung/python/blob/main/%ED%86%B5%EA%B3%84%EB%B6%84%EC%84%9D%EC%8B%9C%EA%B0%81%ED%99%94_Numpy_More.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#행렬의 기본 연산

In [ ]:
import numpy as np

In [ ]:
ls1 = [1,2]
ls2 = [3.4]
ls3 = ls1 + ls2
print(ls3)

[1, 2, 3.4]


In [ ]:
s=0
for i in range(10):
  s += i

assert s == 45, "s는 45여야 합니다." # assert: 반드시 ~해야 한다. ""메세지 생략 가능
# 정답이면 no operation(작동X), 틀리면 assertationError

In [ ]:
# ls목록에 있는 요소의 합계를 구하는 함수
def calsum(ls):
  s = 0
  for e in ls:
    s+=e
  return s

In [ ]:
assert calsum([1,2,3,2])==8, "calsum([1,2,3,2]) 값은 8이어야 합니다." #테스트용으로 자주 사용(정상적으로 만들어졌는지 확인하기 위한 목적)

In [ ]:
def add(l1,l2):
  assert len(l1)==len(l2), "더하기 연산을 위해서는 요소의 길이가 같아야 합니다."
  re=[]
  for i in range(len(l1)):
    re.append(l1[i]+l2[i])
  return re

In [ ]:
ls1 = [1,2]
ls2 = [3,4]
ls3 = add(ls1,ls2)
print(ls3)

[4, 6]


In [ ]:
n1 = np.array([1,2])
n2 = np.array([3,4])
n3 = n1 + n2
print(n3) # numpy는 실제 더하기 연산자를 사용할 수 있어서 list보다 직관적으로 보기에 편리

[4 6]


In [ ]:
n3 = n1 - n2
print(n3)

[-2 -2]


In [ ]:
ls1 = [1,2,3,4]
ls2 = ls1 * 3
print(ls2) # 반복 연산자 but 각각의 요소에 3을 곱하고 싶다면?

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
n1 = np.array([1,2,3,4])
n2 = n1 * 3
print(n2)

[ 3  6  9 12]


평균이 0이고 표준편차가 1인 정규분포 = 표준정규분포

In [ ]:
n2 = n1/3
print(n2)

[0.33333333 0.66666667 1.         1.33333333]


In [ ]:
n1 = np.random.randint(1,1000,100,dtype=int)
print(n1)

[729 748 474 289 886 200 920 949 542 803 865 851 219 469 164 235  29 550
 525 459 999 453 406 333 623 857 305 876 653 452 759 506 841 343 699 298
 163 396 712 130 829 499 367 299 228  42 589 873 368  22 678 270 475 546
 918  16 670 314  77 558  14 973 219 104 929 831 633 657 153 741  56 644
 661 770 555 753 794 381 573 718 838 562  51 435 596 117 703 846 663 528
 508 178  10 810 220 435 209 940 196 259]


In [ ]:
n2 = n1>500
print(n2)

[ True  True False False  True False  True  True  True  True  True  True
 False False False False False  True  True False  True False False False
  True  True False  True  True False  True  True  True False  True False
 False False  True False  True False False False False False  True  True
 False False  True False False  True  True False  True False False  True
 False  True False False  True  True  True  True False  True False  True
  True  True  True  True  True False  True  True  True  True False False
  True False  True  True  True  True  True False False  True False False
 False  True False False]


In [ ]:
n3 = n1[n2]
print(n3)

[729 748 886 920 949 542 803 865 851 550 525 999 623 857 876 653 759 506
 841 699 712 829 589 873 678 546 918 670 558 973 929 831 633 657 741 644
 661 770 555 753 794 573 718 838 562 596 703 846 663 528 508 810 940]


In [ ]:
n1 = np.array([[1,2],[3,4]])
n2 = np.array([4,5])
n3 = np.dot(n1,n2)
print(n3) #행렬의 곱 : 내적(inner product)

[14 32]


In [ ]:
n1 = np.array([1,2,3,4])
n2 = n1.reshape((2,2))
print(n2)

[[1 2]
 [3 4]]


In [ ]:
n3 = np.transpose(n2) #행렬의 대각선을 기준으로 180도 회전 : 전치 행령
print(n3) 

[[1 3]
 [2 4]]


In [ ]:
n3 = np.invert(n2) #반전함수
print(n3)

[[-2 -3]
 [-4 -5]]


In [ ]:
n3 = np.linalg.inv(n2) #역행렬
print(n3)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
n4 = n2.dot(n3)
print(n4)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [ ]:
n1 = np.array([1,2,3,4])
n2 = n1 - 3
print(n2)

[-2 -1  0  1]


In [ ]:
n2 = n1/3
print(n2)

[0.33333333 0.66666667 1.         1.33333333]


통계 관련

In [ ]:
n1 = np.random.randint(1,100,30,dtype=int)
print(n1)

[47 38 43 22 43 14 50 82 60 20 46  7 29 96 50 47 47 85 35 15 69 42  1 85
 84  9  5 60 73 50]


In [ ]:
print("길이:", len(n1))

길이: 30


In [ ]:
print("평균:", n1.mean())

평균: 45.13333333333333


In [ ]:
n2 = n1 - n1.mean()
print("수평 이동한 후 평균:", n2.mean())

수평 이동한 후 평균: 0.0


In [ ]:
print("최대값 위치:", n1.argmax())
print("최대값:", n1[16])
print("최대값:", n1.max())

최대값 위치: 13
최대값: 47
최대값: 96


In [ ]:
print("분산:",n1.var())

분산: 676.7155555555556


In [ ]:
print("표준편차:",n1.std())

표준편차: 26.013757044217115


In [ ]:
n2 = n1/n1.std()
print("스케일 조절한 후 표준 편차:",n2.std())

스케일 조절한 후 표준 편차: 0.9999999999999999


In [ ]:
n1 = np.random.randint(1,100,30,dtype=int)
print("최솟값:", n1.min())
print("중앙값:", np.median(n1))
print("1/4분위값:", np.percentile(n1,25))
print("3/4분위값:", np.percentile(n1,75))

최솟값: 1
중앙값: 40.0
1/4분위값: 23.25
3/4분위값: 69.25


In [ ]:
print(n1)
print("누적 합:", np.cumsum(n1))

[47 38 43 22 43 14 50 82 60 20 46  7 29 96 50 47 47 85 35 15 69 42  1 85
 84  9  5 60 73 50]
누적 합: [  47   85  128  150  193  207  257  339  399  419  465  472  501  597
  647  694  741  826  861  876  945  987  988 1073 1157 1166 1171 1231
 1304 1354]


In [ ]:
n1 = np.arange(1,10)
print(n1)
print("누적 곱:", np.cumprod(n1))

[1 2 3 4 5 6 7 8 9]
누적 곱: [     1      2      6     24    120    720   5040  40320 362880]
