<a href="https://colab.research.google.com/github/yseoyoung/python/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EC%B2%A0%EC%A0%80_%EC%9E%85%EB%AC%B8_%EB%B0%B0%EC%97%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [ ]:
data2 = [0.1, 4, 5, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  4. ,  5. , 12. ,  0.5])

In [ ]:
a1.dtype

dtype('int64')

In [ ]:
a2.dtype

dtype('float64')

In [ ]:
np.array([0.1, 4, 5, 12, 0.5])

array([ 0.1,  4. ,  5. , 12. ,  0.5])

In [ ]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(1,10) # step이 1씩 증가하는 경우 생략 가능

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5) # start가 0부터 시작하고, step이 1씩 증가하는 경우 둘 다 생략 가능

array([0, 1, 2, 3, 4])

In [ ]:
b1 = np.arange(12).reshape(4,3)
b1.shape # 배열의 형태를 알기 위해선 .shape

(4, 3)

In [ ]:
b2 = np.arange(5)
b2.shape

(5,)

In [ ]:
np.linspace(1, 10, 10) # 1부터 10까지 10개의 데이터 생성

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(0, np.pi, 20) # 0부터 pi까지 동일한 간격으로 나눈 20개의 데이터 생성

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.eye(3) # 3 x 3 단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.array(['1.5', '0.62', '2', '3.14', '3,141592']) #문자열이 원소인 Numpy 배열

array(['1.5', '0.62', '2', '3.14', '3,141592'], dtype='<U8')

In [ ]:
num_arr =str

In [ ]:
str_a1 = np.array(['1.597', '1.23', '9', '5'])
num_a1 = str_a1.astype(float) #실수타입으로 변환
num_a1

array([1.597, 1.23 , 9.   , 5.   ])

In [ ]:
str_a1.dtype #유니코드 타입, 문자의 수는 최대 5개

dtype('<U5')

In [ ]:
num_a1.dtype #64비트의 float타입

dtype('float64')

In [ ]:
num_f1 = np.array([10,21,4.75,0.549,5.98])
num_i1 = num_f1.astype(int) #정수로 변환
num_i1

array([10, 21,  4,  0,  5])

In [ ]:
num_f1.dtype

dtype('float64')

In [ ]:
num_i1.dtype

dtype('int64')

In [ ]:
np.random.rand(2,3) #2 x 3의 2차원 배열의 실수 난수 생성

array([[0.14725711, 0.46671838, 0.39831315],
       [0.43553785, 0.64588912, 0.66310174]])

In [ ]:
np.random.rand() # 인자가 없을 시 임의의 난수 생성

0.014649829533724956

In [ ]:
np.random.rand(2,3,4) # 3 x 4의 3차원 배열의 실수 난수 생성

array([[[0.17045394, 0.27119921, 0.98127605, 0.24069644],
        [0.568375  , 0.81411563, 0.46225398, 0.43134582],
        [0.24660648, 0.41984848, 0.23915882, 0.80166794]],

       [[0.45884497, 0.05778234, 0.27399432, 0.56549956],
        [0.91480954, 0.10624291, 0.75064069, 0.79782243],
        [0.15049774, 0.40079252, 0.18718667, 0.27044559]]])

In [ ]:
np.random.randint(10, size=(3,4)) # 0~10사이의 3 x 4인 2차원 배열의 정수 난수 생성

array([[9, 9, 4, 4],
       [0, 9, 7, 2],
       [1, 9, 4, 7]])

In [ ]:
np.random.randint(1, 30) # 1 ~ 30 사이의 정수 난수 생성

28

In [ ]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [ ]:
arr1 + arr2

array([11, 22, 33, 44])

In [ ]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [ ]:
arr2 - arr1

array([ -9, -18, -27, -36])

In [ ]:
arr2 * 2 

array([2, 4, 6, 8])

In [ ]:
arr2 ** 2 #거듭제곱

array([ 1,  4,  9, 16])

In [ ]:
arr1 * arr2 

array([ 10,  40,  90, 160])

In [ ]:
arr1 / arr2

array([10., 10., 10., 10.])

In [ ]:
arr1 > 20

array([False, False,  True,  True])

In [ ]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [ ]:
arr3 = np.arange(5) #배열 생성
arr3

array([0, 1, 2, 3, 4])

In [ ]:
[arr3.sum(), arr3.mean()] # 배열의 합(sum)과 평균(mean)

[10, 2.0]

In [ ]:
[arr3.std(), arr3.var()] #배열의 표준 편차(std)와 분산(var)

[1.4142135623730951, 2.0]

In [ ]:
[arr3.min(), arr3.max()] #배열의 최솟값(min)과 최댓값(max)

[0, 4]

In [ ]:
arr4 = np.arange(1,5)
[arr4.cumsum(), arr4.cumprod()] #배열의 누적합(cumsum)과 누적곱(cumprod)

[array([ 1,  3,  6, 10]), array([ 1,  2,  6, 24])]

In [ ]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [ ]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [ ]:
#행렬곱(matrix product)
A.dot(B) 

array([[0, 1],
       [6, 7]])

In [ ]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [ ]:
#전치행렬(transpose matrix)
A.transpose()

array([[0, 2],
       [1, 3]])

In [ ]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [ ]:
#역행렬(inverse matrix)
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [ ]:
#행렬식(determinant)
np.linalg.det(A)

-2.0

In [ ]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [ ]:
a1[4] # 배열 인덱싱

40

In [ ]:
a1[[1,3,4]] # 여러 개의 원소 인덱싱

array([10, 30, 40])

In [ ]:
a1[5] = 70 # 원소 추가
a1

array([ 0, 10, 20, 30, 40, 70])

In [ ]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
a2[0,2] # 행 위치: 0, 열 위치: 2인 원소 인덱싱

30

In [ ]:
a2[2,2] = 95 # 값 변경
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [ ]:
a2[1] #행위치만 지정하여 행 전체 가져오기

array([40, 50, 60])

In [ ]:
a2[1] = np.array([45,55,65]) # 행전체 값 변경
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [ ]:
a2[1] = [47,57,67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [ ]:
a2[[0,2],[0,1]] #[[행위치1, 행위치2, ...],[열위치1, 열위치2, ...]] --> [0,0]과 [2,1] 원소 출력

array([10, 80])

In [ ]:
#조건에 만족하는 배열 선택
a = np.array([0,1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [ ]:
a[(a%2) == 0]

array([0, 2, 4, 6])

In [ ]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4] # 배열[시작위치:끝위치-1]

array([10, 20, 30])

In [ ]:
b1[:3] #시작위치는 0부터 끝위치-1

array([ 0, 10, 20])

In [ ]:
b1[2:] #2부터 끝까지

array([20, 30, 40, 50])

In [ ]:
b1[2:5] = np.array([25,35,45])
b1 #슬라이싱을 이용해 원소 변경

array([ 0, 10, 25, 35, 45, 50])

In [ ]:
b1[3:6] = 60 #시작위치부터 끝위치-1까지 60으로 값 변경
b1

array([ 0, 10, 25, 60, 60, 60])

In [ ]:
b2 = np.arange(10,100,10).reshape(3,3)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
b2[1:3, 1:3] #배열[행시작위치:행끝위치-1, 열시작위치:열끝위치-1]

array([[50, 60],
       [80, 90]])

In [ ]:
b2[:3,:1] #b2[행 시작위치 0부터 끝위치-1, 열 시작위치 0부터 끝위치-1]

array([[10],
       [40],
       [70]])

In [ ]:
b2[1][0:2] # 행 지정 후 열 슬라이싱

array([40, 50])

In [ ]:
b2[0:2, 1:3] = np.array([[25,35],[55,65]]) #값 변경
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])